package fr.lg30.waynesworld;
import javax.imageio.ImageIO; import javax.swing.*; import javax.swing.border.*; import java.awt.*; import java.awt.image.*; import java.io.*; import java.nio.file.*; import java.util.*;
public final class PatcherPanel extends JPanel {
 private final JLabel file=new JLabel("Aucun fichier"),size=new JLabel("—"),status=new JLabel("Sélectionnez la ROM USA originale"); private final JButton create=button("▶  CRÉER MA ROM",new Color(28,166,61)); private final JCheckBox translation=box("Traduction française LG30",true); private final Map<Cheat,JCheckBox> choices=new EnumMap<>(Cheat.class); private Path selected;
 public PatcherPanel(){setPreferredSize(new Dimension(1500,950));setBackground(new Color(7,11,15));setLayout(new BorderLayout(14,12));setBorder(new EmptyBorder(12,15,12,15));add(banner(),BorderLayout.NORTH);var center=new JPanel(new BorderLayout(12,12));center.setOpaque(false);center.add(selection(),BorderLayout.NORTH);var columns=new JPanel(new GridBagLayout());columns.setOpaque(false);var g=new GridBagConstraints();g.gridy=0;g.fill=GridBagConstraints.BOTH;g.weighty=1;g.insets=new Insets(0,0,0,12);g.gridx=0;g.weightx=.25;columns.add(translation(),g);g.gridx=1;g.weightx=.48;columns.add(cheats(),g);g.gridx=2;g.weightx=.27;g.insets=new Insets(0,0,0,0);columns.add(right(),g);center.add(columns);add(center);add(footer(),BorderLayout.SOUTH);}
 private JComponent banner(){BufferedImage im=image("/ui/wayne-banner.png.b64");return new JComponent(){public Dimension getPreferredSize(){return new Dimension(1500,238);}protected void paintComponent(Graphics g){g.drawImage(im,0,0,getWidth(),getHeight(),null);}};}
 private JPanel selection(){var p=panel("1. SÉLECTION DE LA ROM");p.setLayout(new BorderLayout(18,4));var choose=button("▱  Choisir la ROM Wayne's World (.md)",new Color(37,104,177));choose.addActionListener(e->choose());p.add(choose,BorderLayout.WEST);var info=new JPanel(new GridLayout(3,2,8,5));info.setOpaque(false);info.add(label("Fichier sélectionné :"));info.add(file);info.add(label("Taille :"));info.add(size);info.add(label("Statut :"));info.add(status);p.add(info);var cover=image("/ui/wayne-cover.png.b64");p.add(new JLabel(new ImageIcon(cover.getScaledInstance(255,142,Image.SCALE_SMOOTH))),BorderLayout.EAST);return p;}
 private JPanel translation(){var p=panel("2. TRADUCTION");p.setLayout(new BoxLayout(p,BoxLayout.Y_AXIS));p.add(translation);p.add(Box.createVerticalStrut(15));var d=label("<html>Applique les 183 traductions validées,<br>la région World U / E / J et l'écran<br>d'introduction LG30 / Team Delta Island.</html>");d.setForeground(new Color(185,190,198));p.add(d);return p;}
 private JPanel cheats(){var p=panel("3. CHEATS / OPTIONS DE JEU");p.setLayout(new GridLayout(4,1,8,8));for(Cheat c:Cheat.values()){var b=box(c.label,false);choices.put(c,b);p.add(b);}return p;}
 private JPanel right(){var p=new JPanel(new GridLayout(2,1,0,12));p.setOpaque(false);var creation=panel("4. CRÉATION");creation.setLayout(new BorderLayout(0,12));create.setEnabled(false);create.setFont(create.getFont().deriveFont(Font.BOLD,23f));create.addActionListener(e->create());creation.add(create,BorderLayout.CENTER);creation.add(label("<html>Une nouvelle ROM sera créée.<br>La ROM originale ne sera jamais modifiée.</html>"),BorderLayout.SOUTH);p.add(creation);var info=panel("INFORMATIONS");info.setLayout(new BorderLayout());info.add(label("<html>Wayne's World © 1992<br><br>Sega Mega Drive / Genesis<br><br>Hack réalisé par LG30 / Team Delta Island</html>"));p.add(info);return p;}
 private JPanel footer(){var p=new JPanel(new BorderLayout());p.setOpaque(false);p.add(label("v1.0.0"),BorderLayout.WEST);p.add(label("Pour usage personnel uniquement."),BorderLayout.CENTER);return p;}
 private JPanel panel(String title){var p=new JPanel();p.setBackground(new Color(19,25,31));p.setBorder(new CompoundBorder(new TitledBorder(new LineBorder(new Color(56,65,73),1,true),title,TitledBorder.LEFT,TitledBorder.TOP,new Font("SansSerif",Font.BOLD,18),new Color(65,160,255)),new EmptyBorder(15,18,15,18)));return p;}
 private static JLabel label(String s){var l=new JLabel(s);l.setForeground(new Color(229,232,236));l.setFont(new Font("SansSerif",Font.PLAIN,16));return l;} private static JCheckBox box(String s,boolean on){var b=new JCheckBox(s,on);b.setOpaque(false);b.setForeground(Color.WHITE);b.setFont(new Font("SansSerif",Font.BOLD,17));b.setFocusPainted(false);return b;} private static JButton button(String s,Color c){var b=new JButton(s);b.setBackground(c);b.setForeground(Color.WHITE);b.setFont(new Font("SansSerif",Font.BOLD,17));b.setFocusPainted(false);b.setBorder(new EmptyBorder(18,24,18,24));return b;}
 private static BufferedImage image(String name){try(var in=PatcherPanel.class.getResourceAsStream(name)){return ImageIO.read(new ByteArrayInputStream(Base64.getMimeDecoder().decode(in.readAllBytes())));}catch(Exception e){throw new IllegalStateException("Ressource image invalide: "+name,e);}}
 private void choose(){var fc=new JFileChooser();if(fc.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){selected=fc.getSelectedFile().toPath();try{byte[] b=Files.readAllBytes(selected);file.setText(selected.getFileName().toString());size.setText(b.length+" octets");boolean ok=new RomValidator().isCompatible(b);status.setText(ok?"ROM Wayne's World (USA) compatible":"ROM non reconnue — aucune modification ne sera effectuée");status.setForeground(ok?new Color(62,205,91):new Color(240,68,68));create.setEnabled(ok);}catch(IOException e){status.setText(e.getMessage());create.setEnabled(false);}}}
 private void create(){try{Set<Cheat>s=EnumSet.noneOf(Cheat.class);choices.forEach((c,b)->{if(b.isSelected())s.add(c);});Path out=new RomCreationService().create(selected,selected.toAbsolutePath().getParent(),translation.isSelected(),s);JOptionPane.showMessageDialog(this,"ROM créée : "+out);}catch(Exception e){JOptionPane.showMessageDialog(this,e.getMessage(),"Erreur",JOptionPane.ERROR_MESSAGE);}}
}
